# ASSIGNMENT 1
## Basic Data Exploration and Cleaning Using Pandas

### Submitted By:
Rahul Kumar_
MMDU

### Role:
Data Engineer Fresher

### Objective:
The objective of this assignment is to perform basic data exploration and data cleaning operations using Python Pandas library. This includes loading a CSV dataset, exploring the dataset structure, handling missing values, removing duplicates, performing basic filtering operations, creating derived columns, and saving the cleaned dataset for further analysis.

#  Import Required Libraries

In [3]:
# Importing required library

import pandas as pd

print("Pandas library imported successfully!")

Pandas library imported successfully!

# Question 1: Load a CSV Dataset into a Pandas DataFrame

In this step, the CSV dataset is loaded into a Pandas DataFrame using Pandas library.

In [4]:
# Loading CSV dataset

df = pd.read_csv("data.csv")

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [5]:
# Display first 5 rows

df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,1848495,Teakwood Leathers,Men Brown Leather Formal Shoes,3.5,25,10199.0,60.0,"""₹4,079.00""",INR,http://assets.myntassets.com/assets/images/184...,...,"{""1_star"":5,""2_stars"":3,""3_stars"":3,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",TEA███OD,"[{""size"":""6"",""value"":""25.0cm"",""value_name"":""To...",NaN,"SF-███ MG███AD,█████████R, ███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",formal-shoes
1,21850100,FAUSTO,Men Formal Lace-Up Oxfords Shoes,0.0,0,999.0,1.0,"""₹989.00""",INR,http://assets.myntassets.com/assets/images/218...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,STY███HOR███MAR█████████IVA████████████,"[{""size"":""6"",""value"":""25.5cm"",""value_name"":""To...",NaN,40A███ Ma███ Mo█████████ya ███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",formal-shoes
2,19778366,EZOK,Men Brown Leather Textured Formal Derbys,0.0,0,4299.0,34.0,"""₹2,837.00""",INR,http://assets.myntassets.com/assets/images/197...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Ama███hoe███nd █████████are███,"[{""size"":""6"",""value"":""26.0cm"",""value_name"":""To...",NaN,"C-7███cto███80,█████████r P███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",formal-shoes
3,21869550,San Frissco,Men Genuine Leather Formal Loafers,0.0,0,7995.0,63.0,"""₹2,958.00""",INR,http://assets.myntassets.com/assets/images/218...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,ARY███ FO███EAR█████████PVT██████,"[{""size"":""6"",""value"":""24.9cm"",""value_name"":""To...",NaN,Ary███ fo███ear█████████vt ███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",formal-shoes
4,21931392,Clarks,Men Leather Round Toe Formal Derbys,4.4,7,9999.0,40.0,"""₹5,999.00""",INR,http://assets.myntassets.com/assets/images/219...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":1,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",CLA███ RE███NCE█████████ PV██████,"[{""size"":""6"",""value"":""24.6cm"",""value_name"":""To...",NaN,"Kil███o. ███/ 1█████████, 1███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",formal-shoes

# Question 2: Explore Data (head/tail, shape, columns, data types)

In this step, the structure and basic information of the dataset are explored.

In [6]:
# Display last 5 rows

df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
7,21679542,INVICTUS,Men Leather Formal Derbys,0.0,0,4595.0,74.0,"""₹1,194.00""",INR,http://assets.myntassets.com/assets/images/216...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,ARY███ FO███EAR█████████PVT██████,"[{""size"":""6"",""value"":""25.1cm"",""value_name"":""To...",NaN,Ary███ fo███ear█████████vt ███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",formal-shoes
8,21656954,Fashion Victim,Men Tassel Leather Formal Slip on Shoes,3.5,6,3999.0,72.0,"""₹1,119.00""",INR,http://assets.myntassets.com/assets/images/216...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Rad███Kri███a F█████████b,"[{""size"":""6"",""value"":""24.5cm"",""value_name"":""To...",NaN,"56,███und███Nag█████████ion███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",formal-shoes
9,22609796,HERE&NOW,Men Black Perforated Formal Brogues,3.7,29,2999.0,70.0,"""₹899.00""",INR,http://assets.myntassets.com/assets/images/226...,...,"{""1_star"":5,""2_stars"":3,""3_stars"":0,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",KRU███A E███RPR██████,"[{""size"":""6"",""value"":""25.1cm"",""value_name"":""To...",NaN,"83,███MLA███GAR█████████TAR██████████████████",NaN,"{""applicable_on"":""Orders above Rs. 1099 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",formal-shoes
10,13376884,DAVINCHI,Men Black Solid Formal Leather Slip-On Shoes,0.0,0,6990.0,55.0,"""₹3,145.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",MET███BRA███,"[{""size"":""6"",""value"":""25.3cm"",""value_name"":""To...",NaN,Met███Bra███ Li█████████ldi███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",formal-shoes
11,13411744,CARLO ROMANO,Men Black Solid Burnish Leather Formal Shoes,3.7,23,3998.0,48.0,"""₹2,078.00""",INR,http://assets.myntassets.com/assets/images/134...,...,"{""1_star"":3,""2_stars"":2,""3_stars"":4,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, A Littl...",M/S███EPA███MPE███,"[{""size"":""6"",""value"":""25.7cm"",""value_name"":""To...",NaN,III███ FL███ 17█████████AK ███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",formal-shoes

In [7]:
# Shape of dataset

print(df.shape)

(12, 24)

In [8]:
# Column names

print(df.columns)

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

In [ ]:
# Data types

print(df.dtypes)

# Question 3: Handle Missing Values (identify, fill/drop)

In this step, missing values are identified and handled using appropriate methods.

In [18]:
# Checking missing values in dataset

print(df.isnull().sum())

product_id                 0
title                      0
product_description        0
rating                     0
ratings_count              0
initial_price              0
discount                   0
final_price                0
currency                   0
images                     0
delivery_options           0
product_details            0
breadcrumbs                0
product_specifications     0
amount_of_stars            0
what_customers_said        0
seller_name                0
sizes                      0
videos                    12
seller_information         0
variations                 0
best_offer                 0
more_offers                0
category                   0
dtype: int64

In [12]:
# Selecting numeric columns

numeric_columns = df.select_dtypes(include=['int64', 'float64']).columns

print("Numeric Columns:")
print(numeric_columns)

Numeric Columns:
Index(['product_id', 'rating', 'ratings_count', 'initial_price', 'discount',
       'videos'],
      dtype='object')

In [19]:
# Filling numeric missing values with mean

for col in numeric_columns:
    
    df[col] = df[col].fillna(df[col].mean())

print("Numeric missing values handled successfully!")

Numeric missing values handled successfully!

In [14]:
# Selecting categorical columns

categorical_columns = df.select_dtypes(include=['object']).columns

print("Categorical Columns:")
print(categorical_columns)

Categorical Columns:
Index(['title', 'product_description', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

In [20]:
# Filling categorical missing values with mode

for col in categorical_columns:
    
    df[col] = df[col].fillna(df[col].mode()[0])

print("Categorical missing values handled successfully!")

Categorical missing values handled successfully!

In [ ]:
# Checking missing values again after handling

print(df.isnull().sum())

product_id                 0
title                      0
product_description        0
rating                     0
ratings_count              0
initial_price              0
discount                   0
final_price                0
currency                   0
images                     0
delivery_options           0
product_details            0
breadcrumbs                0
product_specifications     0
amount_of_stars            0
what_customers_said        0
seller_name                0
sizes                      0
videos                    12
seller_information         0
variations                 0
best_offer                 0
more_offers                0
category                   0
dtype: int64

In [23]:
# Handling remaining missing values

df = df.fillna("Not Available")

print(df.isnull().sum())

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
videos                    0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
dtype: int64

# Question 4: Perform Basic Operations (filter rows, select columns)

In this step, basic operations such as selecting columns and filtering rows are performed on the dataset.

In [39]:
# Selecting first two columns

selected_columns = df.iloc[:, :2]

print(selected_columns.head())

   product_id              title
0     1848495  Teakwood Leathers
1    21850100             FAUSTO
2    19778366               EZOK
3    21869550        San Frissco
4    21931392             Clarks

In [40]:

# Filtering rows using numeric column

numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns

filtered_data = df[df[numeric_cols[0]] > df[numeric_cols[0]].mean()]

print(filtered_data.head())

   product_id        title                       product_description  rating  \
1    21850100       FAUSTO          Men Formal Lace-Up Oxfords Shoes     0.0
2    19778366         EZOK  Men Brown Leather Textured Formal Derbys     0.0
3    21869550  San Frissco        Men Genuine Leather Formal Loafers     0.0
4    21931392       Clarks       Men Leather Round Toe Formal Derbys     4.4
5    21524384       FAUSTO                 Men Leather Formal Derbys     0.0

   ratings_count  initial_price  discount  final_price currency  \
1              0          999.0       1.0    "₹989.00"      INR
2              0         4299.0      34.0  "₹2,837.00"      INR
3              0         7995.0      63.0  "₹2,958.00"      INR
4              7         9999.0      40.0  "₹5,999.00"      INR
5              0         1399.0       1.0  "₹1,385.00"      INR

                                              images  ...  \
1  http://assets.myntassets.com/assets/images/218...  ...
2  http://assets.myntassets.com/assets/images/197...  ...
3  http://assets.myntassets.com/assets/images/218...  ...
4  http://assets.myntassets.com/assets/images/219...  ...
5  http://assets.myntassets.com/assets/images/215...  ...

                                               sizes         videos  \
1  [{"size":"6","value":"25.5cm","value_name":"To...  Not Available
2  [{"size":"6","value":"26.0cm","value_name":"To...  Not Available
3  [{"size":"6","value":"24.9cm","value_name":"To...  Not Available
4  [{"size":"6","value":"24.6cm","value_name":"To...  Not Available
5  [{"size":"6","value":"25.5cm","value_name":"To...  Not Available

                                  seller_information variations  \
1  40A███ Ma███ Mo█████████ya ███████████████████...       [{}]
2  C-7███cto███80,█████████r P███████████████████...       [{}]
3  Ary███ fo███ear█████████vt ███████████████████...    [{},{}]
4  Kil███o. ███/ 1█████████, 1███████████████████...       [{}]
5  40A███ Ma███ Mo█████████ya ███████████████████...    [{},{}]

                                          best_offer  \
1  {"applicable_on":"Orders above Rs. 999 (only o...
2  {"applicable_on":"Orders above Rs. 1499 (only ...
3  {"applicable_on":"Orders above Rs. 1499 (only ...
4  {"applicable_on":"Orders above Rs. 1499 (only ...
5  {"applicable_on":"Orders above Rs. 1499 (only ...

                                         more_offers      category   price  \
1  [{"offer_name":"10% Instant Discount on IndusI...  formal-shoes   999.0
2  [{"offer_name":"10% Instant Discount on IndusI...  formal-shoes  4299.0
3  [{"offer_name":"10% Instant Discount on IndusI...  formal-shoes  7995.0
4  [{"offer_name":"10% Instant Discount on IndusI...  formal-shoes  9999.0
5  [{"offer_name":"10% Instant Discount on IndusI...  formal-shoes  1399.0

  quantity total_amount
1        0          0.0
2        0          0.0
3        0          0.0
4        7      69993.0
5        0          0.0

[5 rows x 27 columns]

# Question 5: Remove Duplicates

In this step, duplicate rows are identified and removed from the dataset.

In [30]:
# Checking duplicate rows

print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [31]:
# Removing duplicate rows

df = df.drop_duplicates()

print("Duplicates removed successfully!")

Duplicates removed successfully!

# Question 6: Create a Derived Column (total_amount = price * quantity)

In this step, a new column named total_amount is created using price and quantity columns.

In [35]:
# Creating temporary price and quantity columns

df['price'] = df['initial_price']

df['quantity'] = df['ratings_count']

In [37]:
# Creating derived column

df['total_amount'] = df['price'] * df['quantity']

print("Derived column created successfully!")

print(df[['price', 'quantity', 'total_amount']].head())

Derived column created successfully!
     price  quantity  total_amount
0  10199.0        25      254975.0
1    999.0         0           0.0
2   4299.0         0           0.0
3   7995.0         0           0.0
4   9999.0         7       69993.0

# Question 7: Save the Cleaned Dataset as a New CSV File

In this step, the cleaned dataset is saved as a new CSV file for future analysis.

In [38]:
# Saving cleaned dataset

df.to_csv("cleaned_data.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

# Brief Summary

In this assignment, the dataset was successfully loaded into a Pandas DataFrame and explored using various Pandas functions. Missing values were identified and handled using mean, mode, and fill methods. Basic operations such as selecting columns and filtering rows were performed. Duplicate records were identified and removed from the dataset. A new derived column named total_amount was created using price and quantity columns. Finally, the cleaned dataset was saved as a new CSV file for future analysis and data processing tasks.# Brief Summary